name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          timeout: 300s
          script: |
            set -e
            
            echo "Starting deployment..."

            # Navigate to project directory
            cd /var/www/menastories/menastories.me

            # Pull latest changes
            echo "Pulling latest changes..."
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            # Backend: Install dependencies and restart
            echo "Updating backend..."
            cd Backend
            npm ci --production
            
            # Create storage directories if they don't exist
            mkdir -p storage/images storage/pdfs storage/flipbooks storage/flipbooks/pages storage/docs storage/downloads
            # Set permissions (should already be owned by deploy user)
            chmod -R 755 storage/

            # Restart backend with PM2
            echo "Restarting backend..."
            pm2 restart menastories || pm2 start server.js --name menastories

            # Frontend: Install, build, and deploy
            echo "Building frontend..."
            cd ../Magazine_Website
            npm ci --legacy-peer-deps
            npm run build

            # Ensure build directory has correct ownership
            sudo chown -R deploy:deploy dist/
            sudo chmod -R 755 dist/

            # Reload nginx to pick up any changes (needs sudo permission)
            echo "Reloading nginx..."
            sudo systemctl reload nginx

            # Show PM2 status
            echo "Deployment complete! PM2 status:"
            pm2 status

            echo "✅ Deployment successful!"
